"""Initial Migration

Revision ID: 8dc48f9c5595
Revises: 3ef89580e1eb
Create Date: 2019-10-27 12:32:06.406716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc48f9c5595'
down_revision = '3ef89580e1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=255), nullable=False))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
