"""Initial Migration

Revision ID: ac5b05315a3c
Revises: 0f34b7199c3d
Create Date: 2019-10-26 15:53:38.146355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5b05315a3c'
down_revision = '0f34b7199c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
